# Generated by Django 4.2.6 on 2023-11-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cur_song',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
